# Generated by Django 4.2.26 on 2026-02-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_password_reset_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('priority', 'code'), 'verbose_name': 'Perfi'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'Usuário'},
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_token_h_2771ed_idx',
            old_name='accounts_pas_token_h_0e9f6f_idx',
        ),
    ]
