# Generated by Django 4.2.26 on 2026-02-02 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('autor_nome', models.CharField(max_length=120)),
                ('autor_cargo', models.CharField(blank=True, max_length=80)),
                ('publicado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True)),
                ('tema', models.CharField(blank=True, max_length=120)),
                ('video_url', models.URLField()),
                ('plataforma', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('vimeo', 'Vimeo'), ('mp4', 'MP4 (direto)'), ('other', 'Outro')], default='youtube', max_length=20)),
                ('duracao_segundos', models.PositiveIntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='palavra_pastoral/thumbs/')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='palavra_pastoral/capas/')),
                ('publicado', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('shares_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Palavra Pastoral',
                'verbose_name_plural': 'Palavras Pastorais',
                'ordering': ['-publicado_em', 'ordem', '-id'],
            },
        ),
    ]
