# Generated by Django 4.2.26 on 2026-02-01 21:34

import apps.common.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_encrypt_congregation_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='congregation',
            name='cep',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='congregation',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
        migrations.AlterField(
            model_name='congregation',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='congregations', to='church.church', verbose_name='Igreja'),
        ),
        migrations.CreateModel(
            name='CongregationVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_marcador', models.CharField(blank=True, max_length=50)),
                ('icone_marcador', models.URLField(blank=True)),
                ('zoom_preferido', models.PositiveSmallIntegerField(default=15)),
                ('camada', models.CharField(blank=True, max_length=80)),
                ('congregation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visualization', to='church.congregation')),
            ],
            options={
                'verbose_name': 'Visualização da Congregação',
                'verbose_name_plural': 'Visualizações das Congregações',
            },
        ),
        migrations.CreateModel(
            name='CongregationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('congregation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='church.congregation')),
            ],
            options={
                'verbose_name': 'Localização da Congregação',
                'verbose_name_plural': 'Localizações das Congregações',
            },
        ),
        migrations.CreateModel(
            name='CongregationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_estatica', models.URLField(blank=True)),
                ('imagem_streetview', models.URLField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('galeria_imagens', models.JSONField(blank=True, default=list)),
                ('congregation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='church.congregation')),
            ],
            options={
                'verbose_name': 'Imagens da Congregação',
                'verbose_name_plural': 'Imagens das Congregações',
            },
        ),
        migrations.CreateModel(
            name='CongregationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('data_modificacao', models.DateField(blank=True, null=True)),
                ('historico_eventos', models.JSONField(blank=True, default=list)),
                ('congregation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='church.congregation')),
            ],
            options={
                'verbose_name': 'Histórico da Congregação',
                'verbose_name_plural': 'Históricos das Congregações',
            },
        ),
        migrations.CreateModel(
            name='CongregationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_media', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('numero_avaliacoes', models.PositiveIntegerField(default=0)),
                ('comentarios', models.JSONField(blank=True, default=list)),
                ('congregation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='church.congregation')),
            ],
            options={
                'verbose_name': 'Avaliação da Congregação',
                'verbose_name_plural': 'Avaliações das Congregações',
            },
        ),
        migrations.CreateModel(
            name='CongregationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_local', models.CharField(blank=True, max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('ponto_referencia', models.CharField(blank=True, max_length=255)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=255)),
                ('acessibilidade', models.CharField(blank=True, max_length=255)),
                ('estacionamento', models.CharField(blank=True, max_length=255)),
                ('congregation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='church.congregation')),
            ],
            options={
                'verbose_name': 'Detalhes da Congregação',
                'verbose_name_plural': 'Detalhes das Congregações',
            },
        ),
        migrations.CreateModel(
            name='CongregationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', apps.common.fields.EncryptedCharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('redes_sociais', models.JSONField(blank=True, default=dict)),
                ('congregation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='church.congregation')),
            ],
            options={
                'verbose_name': 'Contato da Congregação',
                'verbose_name_plural': 'Contatos das Congregações',
            },
        ),
    ]
