# Generated by Django 4.2.26 on 2026-02-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_congregation_cep_congregation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregationvisualization',
            name='congregation',
        ),
        migrations.DeleteModel(
            name='CongregationHistory',
        ),
        migrations.DeleteModel(
            name='CongregationVisualization',
        ),
    ]
