# Generated by ChatGPT on 2026-01-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import apps.common.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("church", "0002_encrypt_congregation_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", apps.common.fields.EncryptedCharField(blank=True, max_length=30)),
                ("relationship", models.CharField(blank=True, help_text="Ex.: mãe, pai, tio, avó", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="kids_guardianships", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Responsável",
                "verbose_name_plural": "Responsáveis",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="KidsClass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("age_min", models.PositiveIntegerField(blank=True, help_text="Idade mínima (anos)", null=True)),
                ("age_max", models.PositiveIntegerField(blank=True, help_text="Idade máxima (anos)", null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "congregation",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="kids_classes", to="church.congregation"),
                ),
            ],
            options={
                "verbose_name": "Turma ADMSKIDS",
                "verbose_name_plural": "Turmas ADMSKIDS",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Kid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")], max_length=1)),
                ("allergies", apps.common.fields.EncryptedCharField(blank=True, max_length=255)),
                ("medical_notes", apps.common.fields.EncryptedCharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="admskids/kids")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "congregation",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="kids", to="church.congregation"),
                ),
            ],
            options={
                "verbose_name": "Criança",
                "verbose_name_plural": "Crianças",
                "ordering": ("first_name", "last_name"),
            },
        ),
        migrations.CreateModel(
            name="ClassSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_kids_sessions", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "kids_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="admskids.kidsclass"),
                ),
            ],
            options={
                "verbose_name": "Sessão ADMSKIDS",
                "verbose_name_plural": "Sessões ADMSKIDS",
                "ordering": ("-date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "kid",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="admskids.kid"),
                ),
                (
                    "kids_class",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="admskids.kidsclass"),
                ),
            ],
            options={
                "verbose_name": "Matrícula ADMSKIDS",
                "verbose_name_plural": "Matrículas ADMSKIDS",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="KidGuardian",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "guardian",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="guardian_kids", to="admskids.guardian"),
                ),
                (
                    "kid",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="kid_guardians", to="admskids.kid"),
                ),
            ],
            options={
                "verbose_name": "Vínculo Criança-Responsável",
                "verbose_name_plural": "Vínculos Criança-Responsável",
                "unique_together": {("kid", "guardian")},
            },
        ),
        migrations.CreateModel(
            name="KidAttendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("present", "Presente"), ("absent", "Ausente")], default="present", max_length=10)),
                ("checkin_at", models.DateTimeField(blank=True, null=True)),
                ("checkout_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_by", apps.common.fields.EncryptedCharField(blank=True, help_text="Quem buscou (nome)", max_length=120)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "kid",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendances", to="admskids.kid"),
                ),
                (
                    "session",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendances", to="admskids.classsession"),
                ),
            ],
            options={
                "verbose_name": "Presença ADMSKIDS",
                "verbose_name_plural": "Presenças ADMSKIDS",
                "ordering": ("-checkin_at",),
                "unique_together": {("session", "kid")},
            },
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(fields=("kid", "kids_class"), name="uniq_kid_class_enrollment"),
        ),
        migrations.AddConstraint(
            model_name="classsession",
            constraint=models.UniqueConstraint(fields=("kids_class", "date"), name="uniq_class_date_session"),
        ),
    ]
