# Generated by Django 4.2.26 on 2026-01-24 22:03

import apps.common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admskids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='phone',
            field=apps.common.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='kidattendance',
            name='picked_up_by',
            field=apps.common.fields.EncryptedCharField(blank=True, help_text='Quem buscou (nome)', max_length=255),
        ),
    ]
