# Generated by Django 4.2.26 on 2026-02-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AoVivoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Categoria (Ao Vivo)',
                'verbose_name_plural': 'Categorias (Ao Vivo)',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AoVivoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=180, verbose_name='Subtítulo')),
                ('provider', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('url', 'URL')], default='youtube', max_length=20, verbose_name='Provedor')),
                ('video_url', models.URLField(max_length=500, verbose_name='Link do Vídeo')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='Thumbnail (URL)')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='aovivo.aovivocategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Vídeo (Ao Vivo)',
                'verbose_name_plural': 'Vídeos (Ao Vivo)',
                'ordering': ['-published_at', '-created_at', 'order'],
                'indexes': [models.Index(fields=['is_active', 'provider'], name='aovivo_aovi_is_acti_f7a772_idx'), models.Index(fields=['category', 'is_active'], name='aovivo_aovi_categor_415c57_idx')],
            },
        ),
    ]
